[package]
name = "jqf-codec-core-bench"
version.workspace = true
edition.workspace = true
license.workspace = true
publish = false
rust-version.workspace = true

[features]
allocation-stats = ["jqf-bench-core/allocation-stats"]

[dependencies]
jqf-bench-core = { workspace = true }
jqf-codec-core = { workspace = true }
jqf-codec-json = { workspace = true }
jqf-data = { workspace = true }
jqf-resource = { workspace = true }
jqf-source = { workspace = true }

[[bin]]
name = "jqf-codec-core-bench"
path = "src/main.rs"

[lints]
workspace = true
