//! The 058 W5 shell-completion gate: `tools/completions/jqf.bash` and `jqf.zsh` are GENERATED from the binary's own
//! surfaces (`--help`'s flag table and its pipe-enumerated values, `--list-builtins`' names) by
//! `tools/jqf-completions-gen.py` — one law, two consumers with the help, so a flag/format/dialect/builtin change
//! regenerates the scripts in the same commit.
//!
//! This test runs the generator's own `--check` against the binary under test: it regenerates both scripts in memory
//! and exits nonzero on drift. The standing gate (`make completions`, a commit-tier lane in `tools/jqf-gates.py`) runs
//! the same check against the plain release build; this test is the per-`cargo test` belt.

use std::process::{Command, Stdio};

fn jqf_binary() -> &'static str {
    env!("CARGO_BIN_EXE_jqf")
}

/// The generator lives at the repo root's tools/; integration-test cwd is the crate root (jqf-cli/).
fn generator() -> std::path::PathBuf {
    std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("..")
        .join("tools")
        .join("jqf-completions-gen.py")
}

#[test]
fn completions_match_the_binary_surfaces() {
    assert!(generator().is_file(), "generator missing: {:?}", generator());
    let output = Command::new("python3")
        .arg(generator())
        .arg("--check")
        .arg("--jqf")
        .arg(jqf_binary())
        .env("JQF_NO_CONFIG", "1")
        .stdin(Stdio::null())
        .output()
        .expect("python3 runs the generator");
    assert!(
        output.status.success(),
        "completions --check failed: {}",
        String::from_utf8_lossy(&output.stderr)
    );
}

/// The shipped scripts carry the generated marker and the completion wiring; a hand-rewrite that deleted the marker (or
/// the wiring) is caught here even before the generator's diff runs.
#[test]
fn shipped_scripts_are_generated_and_wired() {
    let bash = std::fs::read_to_string(generator().parent().unwrap().join("completions").join("jqf.bash"))
        .expect("jqf.bash exists");
    let zsh = std::fs::read_to_string(generator().parent().unwrap().join("completions").join("jqf.zsh"))
        .expect("jqf.zsh exists");
    assert!(
        bash.starts_with("# jqf bash completion.") && bash.contains("complete -F _jqf jqf"),
        "jqf.bash is the generated bash completion"
    );
    assert!(
        zsh.starts_with("#compdef jqf") && zsh.contains("compdef _jqf jqf"),
        "jqf.zsh is the generated zsh completion"
    );
    for (name, text) in [("bash", &bash), ("zsh", &zsh)] {
        assert!(
            text.contains("GENERATED by tools/jqf-completions-gen.py"),
            "{name} completion carries the generated marker"
        );
        assert!(
            text.contains("--mismatch-policy"),
            "{name} completion covers the 052 dial"
        );
    }
}
