#compdef jqf
# jqf zsh completion.
# GENERATED by tools/jqf-completions-gen.py from the jqf binary's own surfaces; do not edit.
# Regenerate with `make completions` (or `python3 tools/jqf-completions-gen.py`).

_jqf() {
    local -a opts
    opts=(
        '--input-format:input format:(json jsonc json5 ndjson json-seq toml csv tsv cbor cbor-seq yaml jqft jqfjson jqfb xml html properties ini dotenv messagepack)'
        '--input-dialect:input dialect:(rfc8259 jsonc.trailing@1 jsonc.default@1 json5.document@1 ndjson.strict@1 ndjson.recovering@1 json-seq.strict@1 toml-1.0 toml-1.1 csv.utf8@1 csv.utf8-header@1 csv.rfc4180@1 csv.rfc4180-header@1 tsv.utf8@1 tsv.utf8-header@1 cbor.rfc8949-generic@1 cbor-seq.rfc8742-generic@1 yaml.core@1 yaml.json@1 yaml.failsafe@1 jqft.document@1 jqfjson.document@1 jqfb.document@1 xml.document@1 html.document@1 html.fragment@1 properties.jdk@1 ini.jqf-strict@1 dotenv.jqf-strict@1 messagepack.utf8@1 messagepack.key-equivalence@1)'
        '--old-format:old format:(json jsonc json5 ndjson json-seq toml csv tsv cbor cbor-seq yaml jqft jqfjson jqfb xml html properties ini dotenv messagepack)'
        '--new-format:new format:(json jsonc json5 ndjson json-seq toml csv tsv cbor cbor-seq yaml jqft jqfjson jqfb xml html properties ini dotenv messagepack)'
        '--csv-delimiter:value:'
        '--header'
        '--output-format:output format:(json jsonc json5 ndjson json-seq toml csv tsv cbor cbor-seq yaml jqft jqfjson jqfb xml html properties ini dotenv messagepack render)'
        '--output-dialect:output dialect:(rfc8259 jsonc.trailing-jqf@1 jsonc.default-jqf@1 jsonc.jqf-1.0@1 json5.jqf@1 json5.jqf-1.0@1 ndjson.strict@1 json-seq.jqf@1 toml.jqf-1.0@1 toml.jqf-1.1@1 csv.jqf-utf8@1 csv.jqf-utf8-header@1 csv.jqf-rfc4180@1 csv.jqf-rfc4180-header@1 tsv.jqf-lf@1 tsv.jqf-lf-header@1 cbor.source@1 cbor.preferred@1 cbor.core-deterministic@1 cbor.length-first@1 cbor-seq.jqf@1 yaml.block@1 yaml.jqf-1.0@1 yaml.stream-canonical@1 yaml.single-document@1 jqft.canonical@1 jqfjson.canonical@1 jqfb.canonical@1 xml.source@1 xml.jqf-deterministic@1 html.source@1 html.document-serialize@1 properties.jqf-1.0@1 ini.jqf-1.0@1 dotenv.jqf-1.0@1 messagepack.deterministic@1 messagepack.deterministic-float64@1 render.plain@1 render.gfm-table@1 render.html-table@1 render.grid-table@1 render.tree@1 render.terminal@1 render.shell@1 render.hist@1)'
        '--ndjson-terminator:ndjson terminator:(lf crlf)'
        '--render-header:render header:(present absent)'
        '--render-width:render width:(western cjk)'
        '--render-shape:render shape:(plain table tree)'
        '--render-max-width:value:'
        '(-n --null-input)'{-n,--null-input}
        '(-r --raw-output)'{-r,--raw-output}
        '(-R --raw-input)'{-R,--raw-input}
        '(-s --slurp)'{-s,--slurp}
        (-f --from-file){-f,--from-file}':file:_files'
        (-L --library-path){-L,--library-path}':file:_files'
        '--arg:value:'
        '--argjson:value:'
        (--slurpfile){--slurpfile}':file:_files'
        (--rawfile){--rawfile}':file:_files'
        (--schema){--schema}':file:_files'
        '--args'
        '--jsonargs'
        '--stream'
        '--stream-errors'
        '--seq'
        '--follow'
        '(-e --exit-status)'{-e,--exit-status}
        '(-S --sort-keys)'{-S,--sort-keys}
        '(-j --join-output)'{-j,--join-output}
        '--raw-output0'
        '(-a --ascii-output)'{-a,--ascii-output}
        '--seed:value:'
        '--with-source'
        '--strictness:strictness:(error warn strict lenient)'
        '--mismatch-policy:mismatch policy:(lenient warn strict)'
        '--json-facts'
        '--types-as-strings'
        '--no-json-facts'
        '--unbuffered'
        '(-C --color-output)'{-C,--color-output}
        '(-M --monochrome-output)'{-M,--monochrome-output}
        '(-c --compact-output)'{-c,--compact-output}
        '--indent:value:'
        '--tab'
        '--max-memory-bytes:value:'
        '--max-rss:max rss:(0)'
        '--max-spill-bytes:value:'
        '--max-spill-disk-bytes:value:'
        '--max-iterations:value:'
        '--parallel'
        '--no-parallel'
        '--workers:workers:(auto)'
        '--diagnostics'
        '--explain'
        (--plan-out){--plan-out}':file:_files'
        (--plan-file){--plan-file}':file:_files'
        '--edit'
        '--check'
        '--edit-expand-alias'
        (--diff){--diff}':file:_files'
        (--output){--output}':file:_files'
        '--split-exp:value:'
        (--split-exp-file){--split-exp-file}':file:_files'
        '--in-place'
        '--no-atomic'
        '--list-builtins'
        '--list-formats'
        '--help-format:help format:(json jsonc json5 ndjson json-seq toml csv tsv cbor cbor-seq yaml jqft jqfjson jqfb xml html properties ini dotenv messagepack render)'
        '--explain-code:value:'
        (--config){--config}':file:_files'
        '--no-config'
        '--show-config'
        '(-b --binary)'{-b,--binary}
        '--build-configuration'
        '(-h --help)'{-h,--help}
        '(-V --version)'{-V,--version}
        '*:program or file:_files'
    )
    _arguments -s "$opts[@]"
}

compdef _jqf jqf
