#!/usr/bin/env python3
"""Generate the diagnostic-code tables from the manifest.

Reads `jqf-resource/src/diag/codes.toml` and writes:

  jqf-resource/src/diag/codes.rs      Rust const table + describe()
  bindings/python/jqf/codes.py        Python constants

This script is the only writer of both files. `--check` exits nonzero when
either output is stale.

Usage:
    tools/gates/jqf-diag-codes-gen.py            # regenerate
    tools/gates/jqf-diag-codes-gen.py --check    # verify freshness
"""

import argparse
import sys
import tomllib
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
MANIFEST = ROOT / "jqf-resource" / "src" / "diag" / "codes.toml"
RUST_OUT = ROOT / "jqf-resource" / "src" / "diag" / "codes.rs"
PY_OUT = ROOT / "bindings" / "python" / "jqf" / "codes.py"
STAMP = "tools/gates/jqf-diag-codes-gen.py"


def load():
    with open(MANIFEST, "rb") as f:
        return tomllib.load(f)["code"]


REQUIRED = ("id", "name", "description", "revision", "class", "severity")


def validate(codes):
    # Rows stay in manifest order. describe() is a linear scan; do not
    # assume id order if that ever becomes a binary search.
    seen_ids = {}
    seen_names = {}
    for i, code in enumerate(codes, 1):
        row = f"[[code]] #{i}"
        missing = [key for key in REQUIRED if key not in code]
        if missing:
            fail(f"{row}: missing {', '.join(missing)}")
        code_id, name, description = code["id"], code["name"], code["description"]
        if "\n" in description or "*/" in description:
            fail(f"{row} ({name}): description must be one line and must not contain */")
        if code_id in seen_ids:
            fail(f"duplicate id {code_id} ({seen_ids[code_id]} and {name})")
        if name in seen_names:
            fail(f"duplicate name {name} ({seen_names[name]} and {code_id})")
        seen_ids[code_id] = name
        seen_names[name] = code_id


def fail(message):
    sys.exit(f"{MANIFEST.relative_to(ROOT)}: {message}")


def rust_module(codes):
    lines = []
    lines.append(f"// GENERATED by {STAMP} from codes.toml — do not edit.")
    lines.append("// The manifest is the binding contract's spine; this table is a view of it.")
    lines.append(
        '#![allow(dead_code, reason = "reserved rows and the Python mirror read the same manifest")]'
    )
    lines.append("use super::{RecordClass, Severity};")
    lines.append("")
    for code in codes:
        lines.append(f"/// {code['description']}")
        lines.append(f"pub const {code['name']}: u16 = {code['id']};")
    lines.append("")
    lines.append("/// One registry row: the stable meaning of a code.")
    lines.append("pub struct CodeRow {")
    lines.append("    /// The stable uppercase name (`ROUTE_SELECTED`).")
    lines.append("    pub name: &'static str,")
    lines.append("    /// The semantic revision; a changed meaning is a NEW code, never a repurposed id.")
    lines.append("    pub revision: u16,")
    lines.append("    /// The raise channel: Semantic/Machine/ProgramRaised/Informational.")
    lines.append("    pub class: RecordClass,")
    lines.append("    /// The record's weight: Error/Warning/Info/Trace.")
    lines.append("    pub severity: Severity,")
    lines.append("    /// Whether the id is reserved for a documented v2 producer (never emitted).")
    lines.append("    pub reserved: bool,")
    lines.append("    /// The one-sentence meaning the manifest pins.")
    lines.append("    pub description: &'static str,")
    lines.append("}")
    lines.append("")
    lines.append("/// The closed registry: every emitted code, by id.")
    lines.append("#[rustfmt::skip]")
    lines.append("pub(crate) const CODES: &[(u16, CodeRow)] = &[")
    for code in codes:
        reserved = "true" if code.get("reserved") else "false"
        description = code["description"].replace("\\", "\\\\").replace('"', '\\"')
        lines.append(
            f"    ({code['id']}, CodeRow {{ name: \"{code['name']}\", "
            f"revision: {code['revision']}, class: RecordClass::{code['class']}, "
            f"severity: Severity::{code['severity']}, reserved: {reserved}, "
            f"description: \"{description}\" }}),"
        )
    lines.append("];")
    lines.append("")
    lines.append("/// Looks one code up by id (the public read path `--explain-code` uses).")
    lines.append("#[must_use]")
    lines.append("pub fn describe(code: u16) -> Option<&'static CodeRow> {")
    lines.append("    CODES.iter().find(|(id, _)| *id == code).map(|(_, row)| row)")
    lines.append("}")
    lines.append("")
    return "\n".join(lines)


def python_module(codes):
    lines = []
    lines.append(f"# GENERATED by {STAMP} from codes.toml — do not edit.")
    lines.append('"""Diagnostic codes: the stable binding contract (mirror of the Rust table)."""')
    lines.append("")
    lines.append("class Code:")
    lines.append("    \"\"\"One constant per diagnostic code; the value is the stable id.\"\"\"")
    for code in codes:
        lines.append(f"    {code['name']} = {code['id']}")
    lines.append("")
    lines.append("")
    lines.append("NAME = {")
    for code in codes:
        lines.append(f"    Code.{code['name']}: \"{code['name']}\",")
    lines.append("}")
    lines.append("")
    reserved = [code for code in codes if code.get("reserved")]
    lines.append("RESERVED = {")
    for code in reserved:
        lines.append(f"    Code.{code['name']},")
    lines.append("}")
    lines.append("")
    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="fail on stale output")
    args = parser.parse_args()

    codes = load()
    validate(codes)
    rust = rust_module(codes)
    py = python_module(codes)

    if args.check:
        stale = []
        if not RUST_OUT.exists() or RUST_OUT.read_text() != rust:
            stale.append(str(RUST_OUT.relative_to(ROOT)))
        if not PY_OUT.exists() or PY_OUT.read_text() != py:
            stale.append(str(PY_OUT.relative_to(ROOT)))
        if stale:
            print("stale diagnostic-code tables (run tools/gates/jqf-diag-codes-gen.py): %s"
                  % ", ".join(stale))
            sys.exit(1)
        print("diagnostic-codes: fresh (%d codes)" % len(codes))
        return

    RUST_OUT.parent.mkdir(parents=True, exist_ok=True)
    PY_OUT.parent.mkdir(parents=True, exist_ok=True)
    RUST_OUT.write_text(rust)
    PY_OUT.write_text(py)
    print("wrote %s (%d codes)" % (RUST_OUT.relative_to(ROOT), len(codes)))
    print("wrote %s" % PY_OUT.relative_to(ROOT))


if __name__ == "__main__":
    main()
