#!/usr/bin/env python3
"""Generate the jqf shell completions from the binary's OWN surfaces.

jqf's bash and zsh completions are generated from the same acceptance tables
the help is generated from — one law, two consumers.

The sources are the binary's own generated surfaces, never a hand-written
copy of the flag surface:

  * `--help` — the flag table. Every flag line in the Options section yields
    its short/long spellings, and a pipe-enumerated value spec
    (`--input-format json|ndjson|...`, `--mismatch-policy lenient|warn|strict`)
    becomes the completion words directly: whatever the help advertises is
    what the completion offers, so a flag, format, dialect, or position added
    to the acceptance tables joins the completions without a second list.
  * `--list-builtins` — the program slot completes with builtin names (the
    `/arity` suffix stripped; a bonus, bash-side).

The discipline is the diag-code generator's: this script is the ONLY writer of
`tools/completions/jqf.bash` and `tools/completions/jqf.zsh`, and `--check`
exits nonzero when a shipped file drifted from what the binary says today.
`--check` is the freshness gate (`cargo test -p jqf-cli completions` runs it
against the test binary).

Usage:
    tools/jqf-completions-gen.py [--jqf PATH]            # regenerate both scripts
    tools/jqf-completions-gen.py --check [--jqf PATH]    # verify freshness
"""
import argparse
import os
import re
import subprocess
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
COMPLETIONS_DIR = os.path.join(ROOT, "tools", "completions")
BASH = os.path.join(COMPLETIONS_DIR, "jqf.bash")
ZSH = os.path.join(COMPLETIONS_DIR, "jqf.zsh")
DEFAULT_RELEASE_JQF = os.path.join(ROOT, "target", "release", "jqf")

# The marker every regenerate stamps; --check verifies it is present, so a
# hand-rewrite of a script cannot masquerade as generated.
MARKER = "# GENERATED by tools/jqf-completions-gen.py from the jqf binary's own surfaces; do not edit."

# One flag line in the rendered help's Options section:
#   -n, --null-input
#   --input-format json|ndjson|...
#   -C, --color-output        colorize JSON output
FLAG_RE = re.compile(r"^  (?:(?P<short>-[A-Za-z]), )?(?P<long>--[a-z0-9-]+)(?P<tail>.*)$")

# A value-spec placeholder (N, ID, N%, NAME VALUE, ...): uppercase-led tokens
# are names of values, not values, and are dropped from the word list.
PLACEHOLDER_RE = re.compile(r"^[A-Z][A-Z0-9]*%?$")

# The flags whose value is a file (or whose LAST value is one): completed
# with files. The FILE/DIR/PATH placeholders cover most; the NAME-prefixed
# pairs need the explicit set because their FIRST value is a name.
FILE_FLAGS = frozenset(
    {
        "-f", "--from-file",
        "-L", "--library-path",
        "--slurpfile",
        "--rawfile",
        "--plan-out",
        "--plan-file",
        "--output",
        "--diff",
    }
)
FILE_WORDS = frozenset({"FILE", "DIR", "PATH"})


def run(jqf, args):
    """Runs one surface command; the surfaces are commands, so they never read stdin."""
    completed = subprocess.run(
        [jqf, *args],
        input=b"",
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        timeout=120,
    )
    if completed.returncode != 0:
        raise SystemExit(
            f"completions-gen: {jqf} {' '.join(args)} exited {completed.returncode}: "
            f"{completed.stderr.decode('utf-8', 'replace').strip()}"
        )
    return completed.stdout.decode("utf-8", "replace")


def parse_flags(help_text):
    """Every flag in the help's Options section, with its value kind.

    Returns a list of (short, long, kind, value_words, takes_value):
      kind is "words" (pipe-enumerated value), "file" (file completion), or
      "none" (no completion words). The value words ARE the help's own
      enumeration, split on `|` with placeholder tokens dropped — so the
      completion cannot offer a spelling the parser does not accept.
      takes_value is whether the flag consumes a following argument.
    """
    flags = []
    in_options = False
    for line in help_text.splitlines():
        if line == "Options:":
            in_options = True
            continue
        if not in_options:
            continue
        match = FLAG_RE.match(line)
        if not match:
            continue
        short = match.group("short")
        long_ = match.group("long")
        tail = match.group("tail")
        # A value spec is separated from the flag by EXACTLY one space
        # (`--max-memory-bytes N`); a longer run is an inline description
        # (`-C, --color-output        colorize JSON output`), which is not a
        # value the flag consumes.
        takes_value = tail.startswith(" ") and not tail.startswith("  ")
        tail = tail.strip()
        if "|" in tail:
            tokens = tail.split("|")
            if any(PLACEHOLDER_RE.match(token) for token in tokens):
                words = []
                kind = "none"
            else:
                words = tokens
                kind = "words"
        elif (short or long_) in FILE_FLAGS:
            words = []
            kind = "file"
        elif tail and tail.split()[0] in FILE_WORDS:
            words = []
            kind = "file"
        else:
            words = []
            kind = "none"
        flags.append((short, long_, kind, words, takes_value))
    return flags


def builtin_names(builtins_text):
    """The `--list-builtins` lines are `name/arity`; the program slot
    completes with the bare names (a name at several arities is one word)."""
    names = []
    for line in builtins_text.splitlines():
        if "/" in line:
            line = line.split("/", 1)[0]
        if line not in names:
            names.append(line)
    return names


def render_bash(flags, builtins):
    enum_arms = []
    file_names = []
    value_names = []
    for short, long_, kind, words, takes_value in flags:
        names = "|".join(name for name in (short, long_) if name)
        if kind == "words":
            quoted = 'compgen -W "%s" -- "$cur"' % " ".join(words)
            enum_arms.append(
                "        %s) COMPREPLY=( $(%s) ); return 0 ;;" % (long_, quoted)
            )
        elif kind == "file":
            file_names.append(names)
        elif takes_value:
            # The flag consumes its argument (a number, a name, an id); the
            # value is not word- or file-completable, so offer nothing.
            value_names.append(names)
        # A boolean flag falls through: `jqf -n --<tab>` still completes flags
        # and a later positional still gets files.
    flag_words = " ".join(
        sorted(set(long_ for _, long_, _, _, _ in flags) | {s for s, _, _, _, _ in flags if s})
    )
    builtin_words = " ".join(builtins)

    lines = []
    lines.append("# jqf bash completion.")
    lines.append(MARKER)
    lines.append("# Regenerate with `python3 tools/jqf-completions-gen.py`.")
    lines.append("")
    lines.append("_jqf() {")
    lines.append("    local cur prev")
    lines.append('    cur="${COMP_WORDS[COMP_CWORD]}"')
    lines.append('    prev="${COMP_WORDS[COMP_CWORD-1]}"')
    lines.append("")
    lines.append('    case "$prev" in')
    lines.extend(enum_arms)
    if file_names:
        lines.append("        " + "|".join(file_names) + ")")
        lines.append('            COMPREPLY=( $(compgen -f -- "$cur") ); return 0 ;;')
    if value_names:
        lines.append("        " + "|".join(value_names) + ")")
        lines.append("            return 0 ;;")
    lines.append("    esac")
    lines.append("")
    lines.append('    if [[ "$cur" == -* ]]; then')
    lines.append('        COMPREPLY=( $(compgen -W "%s" -- "$cur") )' % flag_words)
    lines.append("    elif [[ $COMP_CWORD -eq 1 ]]; then")
    lines.append("        # The first positional is the PROGRAM; suggest the builtins.")
    lines.append('        COMPREPLY=( $(compgen -W "%s" -- "$cur") )' % builtin_words)
    lines.append("    else")
    lines.append('        COMPREPLY=( $(compgen -f -- "$cur") )')
    lines.append("    fi")
    lines.append("    return 0")
    lines.append("}")
    lines.append("")
    lines.append("complete -F _jqf jqf")
    lines.append("")
    return "\n".join(lines)


def render_zsh(flags):
    opts = []
    for short, long_, kind, words, takes_value in flags:
        if kind == "words":
            label = long_.removeprefix("--").replace("-", " ")
            opts.append("        '%s:%s:(%s)'" % (long_, label, " ".join(words)))
        elif kind == "file":
            names = ",".join(name for name in (short, long_) if name)
            excl = "(" + " ".join(name for name in (short, long_) if name) + ")"
            opts.append("        %s{%s}':file:_files'" % (excl, names))
        elif takes_value:
            opts.append("        '%s:value:'" % long_)
        elif short:
            opts.append("        '(%s %s)'{%s,%s}" % (short, long_, short, long_))
        else:
            opts.append("        '%s'" % long_)
    opts.append("        '*:program or file:_files'")

    lines = []
    lines.append("# jqf zsh completion.")
    lines.append(MARKER)
    lines.append("# Regenerate with `python3 tools/jqf-completions-gen.py`.")
    lines.append("")
    lines.append("_jqf() {")
    lines.append("    local -a opts")
    lines.append("    opts=(")
    lines.extend(opts)
    lines.append("    )")
    lines.append('    _arguments -s "$opts[@]"')
    lines.append("}")
    lines.append("")
    lines.append("compdef _jqf jqf")
    lines.append("")
    return "\n".join(lines)


def generate(jqf):
    help_text = run(jqf, ["--help"])
    builtins_text = run(jqf, ["--list-builtins"])
    flags = parse_flags(help_text)
    if not flags:
        raise SystemExit("completions-gen: no flags parsed from --help; the surface changed shape")
    return render_bash(flags, builtin_names(builtins_text)), render_zsh(flags)


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--jqf", default=DEFAULT_RELEASE_JQF)
    parser.add_argument(
        "--check",
        action="store_true",
        help="regenerate in memory and exit nonzero if a shipped script drifted",
    )
    args = parser.parse_args()
    if not os.path.isfile(args.jqf) or not os.access(args.jqf, os.X_OK):
        print(f"completions-gen: no executable at {args.jqf}", file=sys.stderr)
        return 2
    bash, zsh = generate(args.jqf)
    expected = {BASH: bash, ZSH: zsh}
    if args.check:
        missing = [path for path in expected if not os.path.isfile(path)]
        if missing:
            for path in missing:
                print(f"completions-gen: MISSING {os.path.relpath(path, ROOT)}", file=sys.stderr)
            return 1
        drifted = [
            path
            for path, content in expected.items()
            if open(path, encoding="utf-8").read() != content
        ]
        if drifted:
            for path in drifted:
                print(
                    f"completions-gen: DRIFTED {os.path.relpath(path, ROOT)} "
                    f"(regenerate with tools/jqf-completions-gen.py)",
                    file=sys.stderr,
                )
            return 1
        print("completions-gen: GREEN (bash + zsh match the binary's surfaces)")
        return 0
    os.makedirs(COMPLETIONS_DIR, exist_ok=True)
    for path, content in expected.items():
        with open(path, "w", encoding="utf-8") as handle:
            handle.write(content)
        print(f"completions-gen: wrote {os.path.relpath(path, ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
