#!/usr/bin/env python3
"""Generate REFERENCE.md from the jqf binary's OWN surfaces.

Assembles the agent-facing document from the binary's own generated surfaces
— `--help`, `--list-builtins`, `--list-formats`, and `--explain-code <id>` for
every code in the diagnostic-code manifest — so the doc an agent reads can
never describe a jqf that does not exist (plan 055 part B; the surfaces
themselves are plan 053).

The discipline is the diag-code generator's: this script is the ONLY writer of
REFERENCE.md, and `--check` exits nonzero when the shipped file drifted from what
the binary says today. The gate (`make reference`) runs the plain release
binary — a freshness answer does not depend on the optimizer — and is wired
into the standing battery at the `commit` tier (measured ~1 s: one help dump,
one builtin dump, one format dump, and one explain-code run per live code).

The prose sections (measurement laws, provenance) are the stable laws the
tree already pins; the surface sections are verbatim binary dumps. A wave that
changes a flag, a format, a dialect, a builtin, or a diagnostic code changes
this file in the same commit — the gate refuses a drift in either direction.

Usage:
    tools/jqf-reference-gen.py [--jqf PATH]            # regenerate REFERENCE.md
    tools/jqf-reference-gen.py --check [--jqf PATH]    # verify freshness
"""
import argparse
import os
import subprocess
import sys
import tomllib

from jqfgate import proc

REFERENCE_MD = os.path.join(proc.ROOT, "REFERENCE.md")
MANIFEST = os.path.join(proc.ROOT, "jqf-resource", "src", "diag", "codes.toml")

# The generation marker every regenerate stamps; --check verifies it is the
# first line, so a hand-rewrite of the file cannot masquerade as generated.
MARKER = "<!-- GENERATED by tools/jqf-reference-gen.py from the jqf binary's own surfaces; do not edit. -->"


def run(jqf, args, stdin=b""):
    """Runs one surface command; the surfaces are commands, so they never read stdin."""
    completed = proc.run_gate(
        jqf, args,
        input=stdin,
        timeout=120,
    )
    if completed.returncode != 0:
        raise SystemExit(
            f"reference: {jqf} {' '.join(args)} exited {completed.returncode}: "
            f"{completed.stderr.decode('utf-8', 'replace').strip()}"
        )
    return completed.stdout.decode("utf-8", "replace")


def manifest_codes():
    with open(MANIFEST, "rb") as handle:
        return tomllib.load(handle)["code"]


def render(jqf):
    help_text = run(jqf, ["--help"]).rstrip("\n")
    builtins = run(jqf, ["--list-builtins"]).rstrip("\n")
    formats = run(jqf, ["--list-formats"]).rstrip("\n")

    codes = []
    for code in manifest_codes():
        page = run(jqf, ["--explain-code", str(code["id"])]).strip()
        codes.append((code["id"], page))

    lines = []
    lines.append(MARKER)
    lines.append("")
    lines.append("# REFERENCE.md — the jqf CLI reference")
    lines.append("")
    lines.append(
        "This document is assembled from the binary's own generated surfaces: "
        "`--help`, `--list-builtins`, `--list-formats`, and the diagnostic-code "
        "registry (`--explain-code`). Every fenced block below is a verbatim "
        "dump of one CLI command, so this doc can never describe a jqf that "
        "does not exist. If a section disagrees with the binary, the binary is "
        "the truth and this file is stale — `make reference` regenerates it and "
        "the `reference` gate fails until the drift is resolved."
    )
    lines.append("")
    lines.append("## The measurement laws")
    lines.append("")
    lines.append(
        "- **`make pgo` builds `target/pgo/jqf`, the only binary a published "
        "number or A/B verdict may come from.** A plain `cargo build --release` "
        "binary measures measurably slower and is not comparable to any PGO "
        "row; a plain-release number is smoke, not evidence. `jqf --diagnostics` "
        "prints `build=pgo profile=... allocator=...` (or `build=plain "
        "profile=none`) before the request runs."
    )
    lines.append(
        "- **Standing measurement tooling.** `make bench`, `make csv-ladder`, "
        "`make cross-format-ladder`, `make ttfb`, and `make broad-bench` are "
        "the on-demand ladders and cross-tool comparisons — directional "
        "instruments, not gates; they assert correctness and attribute every "
        "row to the binary that produced it. `make pgo-fresh` proves the PGO "
        "binary was trained at HEAD."
    )
    lines.append(
        "- **Gates are tiered.** `make gates-commit` is the fast per-commit "
        "loop; `make gates-branch` / `make gates` are the full battery at "
        "branch completion and merge. Every claim quotes the driver's summary "
        "table and its tier (`gates: tier=... lanes=... pass=... fail=... "
        "GREEN|RED`)."
    )
    lines.append(
        "- **Receipts are the evidence, and the repo ships tools, not "
        "receipts.** Benchmark receipts live out-of-tree (each campaign pins "
        "its own baseline and passes it to `tools/jqf-broad-bench-delta.py`); "
        "the fuzz battery is `make fuzz` "
        "(every receipt, every commit); the jq byte-oracle corpus, jq's own "
        "test suites, and the force-route differential are standing gates. "
        "Lane membership is `tools/gates.toml`; working rules are `AGENTS.md`."
    )
    lines.append("")
    lines.append("## Binary provenance")
    lines.append("")
    lines.append(
        "`jqf --diagnostics` prints one provenance line on every request, "
        "before it runs: `build=pgo profile=<workload>.<triple>.<commit>."
        "<digest> allocator=<name>` — or `build=plain profile=none`. `make pgo` "
        "regenerates the profile, so `target/pgo/jqf` is always trained on the "
        "code it was compiled from; `make pgo-fresh` fails when the profile's "
        "training commit is not HEAD."
    )
    lines.append("")
    lines.append("## Flag surface (`--help`)")
    lines.append("")
    lines.append("```text")
    lines.append(help_text)
    lines.append("```")
    lines.append("")
    lines.append("## Formats and dialects (`--list-formats`)")
    lines.append("")
    lines.append("```text")
    lines.append(formats)
    lines.append("```")
    lines.append("")
    lines.append("## Builtin inventory (`--list-builtins`)")
    lines.append("")
    lines.append("```text")
    lines.append(builtins)
    lines.append("```")
    lines.append("")
    lines.append("## Diagnostic codes (`--explain-code`)")
    lines.append("")
    lines.append("One row per code; the stable meaning is the manifest's (`jqf-resource/src/diag/codes.toml`),")
    lines.append("which `tools/jqf-diag-codes-gen.py` mirrors into the binary's registry.")
    lines.append("")
    lines.append("| id | page |")
    lines.append("|----|------|")
    for code_id, page in codes:
        # The page is one `code:/id:/revision:/class:/severity:/meaning:` block
        # per code; fold it into one table row for readability.
        fields = {}
        for line in page.splitlines():
            if ": " in line:
                key, _, value = line.partition(": ")
                fields[key.strip()] = value.strip()
        name = fields.get("code", "?")
        meaning = fields.get("meaning", "?")
        meaning = meaning.replace("|", "\\|").replace("\n", " ")
        lines.append(f"| {code_id} | `{name}` — {meaning} |")
    lines.append("")
    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="fail on stale REFERENCE.md")
    parser.add_argument(
        "--jqf",
        default=proc.DEFAULT_RELEASE_JQF,
        help="the jqf binary to read surfaces from (default: target/release/jqf)",
    )
    args = parser.parse_args()

    if not os.path.isfile(args.jqf) or not os.access(args.jqf, os.X_OK):
        print(f"reference: no executable at {args.jqf}", file=sys.stderr)
        return 2

    rendered = render(args.jqf) + "\n"

    if args.check:
        if not os.path.exists(REFERENCE_MD):
            print("reference: REFERENCE.md is missing (run tools/jqf-reference-gen.py)", file=sys.stderr)
            return 1
        shipped = open(REFERENCE_MD, encoding="utf-8").read()
        if shipped != rendered:
            print("reference: REFERENCE.md is STALE (run tools/jqf-reference-gen.py)", file=sys.stderr)
            return 1
        print(f"reference: fresh ({len(manifest_codes())} codes, {len(rendered.splitlines())} lines)")
        return 0

    with open(REFERENCE_MD, "w", encoding="utf-8") as handle:
        handle.write(rendered)
    print(f"wrote {os.path.relpath(REFERENCE_MD, proc.ROOT)} ({len(rendered.splitlines())} lines)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
