// GENERATED by tools/gates/jqf-diag-codes-gen.py from codes.toml — do not edit.
// The manifest is the binding contract's spine; this table is a view of it.
#![allow(dead_code, reason = "reserved rows and the Python mirror read the same manifest")]
use super::{RecordClass, Severity};

/// The decode route that served the request.
pub const ROUTE_SELECTED: u16 = 1;
/// Ledger totals read at run end.
pub const COST_SNAPSHOT: u16 = 2;
/// One exact-to-binary64 contagion crossing (the exact-number law's fuzzy edge).
pub const PRECISION_BOUNDARY: u16 = 3;
/// Cannot iterate over a non-iterable value.
pub const RAISE_ITERATE: u16 = 4;
/// Cannot index a non-indexable value.
pub const RAISE_INDEX: u16 = 5;
/// Object-key mismatch (dynamic key of the wrong kind).
pub const RAISE_OBJECT_KEY: u16 = 6;
/// Length requested over a non-length-able value.
pub const RAISE_NO_LENGTH: u16 = 7;
/// Keys requested over a non-keys-able value.
pub const RAISE_NO_KEYS: u16 = 8;
/// Slice bounds are not integers.
pub const RAISE_SLICE_INDICES: u16 = 9;
/// Arithmetic operator over mismatched value kinds.
pub const RAISE_ARITHMETIC: u16 = 10;
/// Division by zero.
pub const RAISE_DIVIDE_BY_ZERO: u16 = 11;
/// Remainder by a divisor that truncates to zero.
pub const RAISE_REMAINDER_BY_ZERO: u16 = 12;
/// Retired exact-division diagnostic retained for decoding older records.
pub const RAISE_NONTERMINATING: u16 = 13;
/// Binary64-path overflow (the reserved numeric-range class).
pub const RAISE_NUMERIC_RANGE: u16 = 14;
/// `halt` or `halt_error` terminated the run.
pub const RAISE_HALT: u16 = 15;
/// error/0 or error/1 raised a value; payload carries the catchable text.
pub const RAISE_PROGRAM: u16 = 16;
/// Input violates the selected format or dialect.
pub const MACHINE_INPUT: u16 = 17;
/// A semantic value cannot be represented by the target.
pub const MACHINE_REPRESENTATION: u16 = 18;
/// No physical route satisfies an exact requirement.
pub const MACHINE_REQUIREMENT: u16 = 19;
/// A provider or route identity does not belong to this carrier.
pub const MACHINE_ROUTE_MISMATCH: u16 = 20;
/// A tag identity is invalid for the target codec.
pub const MACHINE_INVALID_TAG: u16 = 21;
/// Distinct stored tag identities collide in the target codec.
pub const MACHINE_COLLIDING_TAGS: u16 = 22;
/// Request accounting rejected an operation.
pub const MACHINE_RESOURCE: u16 = 23;
/// Host cancellation stopped the operation.
pub const MACHINE_CANCELLED: u16 = 24;
/// The request deadline expired.
pub const MACHINE_DEADLINE: u16 = 25;
/// Checked non-resource arithmetic overflowed.
pub const MACHINE_OVERFLOW: u16 = 26;
/// Allocation outside a foundation tracked owner failed.
pub const MACHINE_ALLOCATION: u16 = 27;
/// An internal codec or engine contract was violated.
pub const MACHINE_INTERNAL_CONTRACT: u16 = 29;
/// The host output sink failed.
pub const MACHINE_SINK: u16 = 30;
/// The run could not start: an invalid program, codec, format, dialect, or requirement, before any input was read.
pub const MACHINE_SETUP: u16 = 31;
/// A root string dumped raw contains a literal NUL byte, which this process's raw NUL-terminator framing (--raw-output0) cannot represent.
pub const MACHINE_RAW_NUL: u16 = 32;
/// The cooperative work quantum could not be created: an invalid --cooperative-credits value (a setup failure, pre-input).
pub const MACHINE_CREDITS: u16 = 37;
/// The allocator-level physical memory ceiling was exceeded (the RSS governor). Distinct from `MACHINE_RESOURCE`: the accounted rejection is the request ledger's own ceiling, this one is the process's real resident set.
pub const MACHINE_MEMORY: u16 = 36;
/// A date, time, or date-time was rendered as canonical RFC 3339 text because the target has no native temporal spelling.
pub const PROJECTION_TEMPORAL: u16 = 33;
/// A tagged value was published as its bare payload because the target has no native tag spelling.
pub const PROJECTION_TAG: u16 = 34;
/// A byte string was rendered as base64url text (RFC 8949 section 6.5) because the target has no native byte-string spelling.
pub const PROJECTION_BYTES: u16 = 35;
/// The mismatch dial's capped, aggregated warn report: one record per run, named after the run, carrying the per-cell counts.
pub const MISMATCH_WARN: u16 = 38;
/// A mismatch cell raised under the strict dial; the payload names the cell.
pub const MISMATCH_STRICT: u16 = 39;
/// A ~generator init/update/extract emitted two or more values on one pull: one state, one emission, per pull.
pub const RAISE_ENGINE_CARDINALITY: u16 = 40;
/// Reserved: a projected route validated a corrupt byte the program never read.
pub const FRONTIER_VALIDATION: u16 = 100;

/// One registry row: the stable meaning of a code.
pub struct CodeRow {
    /// The stable uppercase name (`ROUTE_SELECTED`).
    pub name: &'static str,
    /// The semantic revision; a changed meaning is a NEW code, never a repurposed id.
    pub revision: u16,
    /// The raise channel: Semantic/Machine/ProgramRaised/Informational.
    pub class: RecordClass,
    /// The record's weight: Error/Warning/Info/Trace.
    pub severity: Severity,
    /// Whether the id is reserved for a documented v2 producer (never emitted).
    pub reserved: bool,
    /// The one-sentence meaning the manifest pins.
    pub description: &'static str,
}

/// The closed registry: every emitted code, by id.
#[rustfmt::skip]
pub(crate) const CODES: &[(u16, CodeRow)] = &[
    (1, CodeRow { name: "ROUTE_SELECTED", revision: 1, class: RecordClass::Informational, severity: Severity::Info, reserved: false, description: "The decode route that served the request." }),
    (2, CodeRow { name: "COST_SNAPSHOT", revision: 1, class: RecordClass::Informational, severity: Severity::Info, reserved: false, description: "Ledger totals read at run end." }),
    (3, CodeRow { name: "PRECISION_BOUNDARY", revision: 1, class: RecordClass::Informational, severity: Severity::Info, reserved: false, description: "One exact-to-binary64 contagion crossing (the exact-number law's fuzzy edge)." }),
    (4, CodeRow { name: "RAISE_ITERATE", revision: 1, class: RecordClass::Semantic, severity: Severity::Error, reserved: false, description: "Cannot iterate over a non-iterable value." }),
    (5, CodeRow { name: "RAISE_INDEX", revision: 1, class: RecordClass::Semantic, severity: Severity::Error, reserved: false, description: "Cannot index a non-indexable value." }),
    (6, CodeRow { name: "RAISE_OBJECT_KEY", revision: 1, class: RecordClass::Semantic, severity: Severity::Error, reserved: false, description: "Object-key mismatch (dynamic key of the wrong kind)." }),
    (7, CodeRow { name: "RAISE_NO_LENGTH", revision: 1, class: RecordClass::Semantic, severity: Severity::Error, reserved: false, description: "Length requested over a non-length-able value." }),
    (8, CodeRow { name: "RAISE_NO_KEYS", revision: 1, class: RecordClass::Semantic, severity: Severity::Error, reserved: false, description: "Keys requested over a non-keys-able value." }),
    (9, CodeRow { name: "RAISE_SLICE_INDICES", revision: 1, class: RecordClass::Semantic, severity: Severity::Error, reserved: false, description: "Slice bounds are not integers." }),
    (10, CodeRow { name: "RAISE_ARITHMETIC", revision: 1, class: RecordClass::Semantic, severity: Severity::Error, reserved: false, description: "Arithmetic operator over mismatched value kinds." }),
    (11, CodeRow { name: "RAISE_DIVIDE_BY_ZERO", revision: 1, class: RecordClass::Semantic, severity: Severity::Error, reserved: false, description: "Division by zero." }),
    (12, CodeRow { name: "RAISE_REMAINDER_BY_ZERO", revision: 1, class: RecordClass::Semantic, severity: Severity::Error, reserved: false, description: "Remainder by a divisor that truncates to zero." }),
    (13, CodeRow { name: "RAISE_NONTERMINATING", revision: 1, class: RecordClass::Semantic, severity: Severity::Error, reserved: false, description: "Retired exact-division diagnostic retained for decoding older records." }),
    (14, CodeRow { name: "RAISE_NUMERIC_RANGE", revision: 1, class: RecordClass::Semantic, severity: Severity::Error, reserved: false, description: "Binary64-path overflow (the reserved numeric-range class)." }),
    (15, CodeRow { name: "RAISE_HALT", revision: 1, class: RecordClass::Machine, severity: Severity::Warning, reserved: false, description: "`halt` or `halt_error` terminated the run." }),
    (16, CodeRow { name: "RAISE_PROGRAM", revision: 1, class: RecordClass::ProgramRaised, severity: Severity::Error, reserved: false, description: "error/0 or error/1 raised a value; payload carries the catchable text." }),
    (17, CodeRow { name: "MACHINE_INPUT", revision: 1, class: RecordClass::Machine, severity: Severity::Error, reserved: false, description: "Input violates the selected format or dialect." }),
    (18, CodeRow { name: "MACHINE_REPRESENTATION", revision: 1, class: RecordClass::Machine, severity: Severity::Error, reserved: false, description: "A semantic value cannot be represented by the target." }),
    (19, CodeRow { name: "MACHINE_REQUIREMENT", revision: 1, class: RecordClass::Machine, severity: Severity::Error, reserved: false, description: "No physical route satisfies an exact requirement." }),
    (20, CodeRow { name: "MACHINE_ROUTE_MISMATCH", revision: 1, class: RecordClass::Machine, severity: Severity::Error, reserved: false, description: "A provider or route identity does not belong to this carrier." }),
    (21, CodeRow { name: "MACHINE_INVALID_TAG", revision: 1, class: RecordClass::Machine, severity: Severity::Error, reserved: false, description: "A tag identity is invalid for the target codec." }),
    (22, CodeRow { name: "MACHINE_COLLIDING_TAGS", revision: 1, class: RecordClass::Machine, severity: Severity::Error, reserved: false, description: "Distinct stored tag identities collide in the target codec." }),
    (23, CodeRow { name: "MACHINE_RESOURCE", revision: 1, class: RecordClass::Machine, severity: Severity::Error, reserved: false, description: "Request accounting rejected an operation." }),
    (24, CodeRow { name: "MACHINE_CANCELLED", revision: 1, class: RecordClass::Machine, severity: Severity::Error, reserved: false, description: "Host cancellation stopped the operation." }),
    (25, CodeRow { name: "MACHINE_DEADLINE", revision: 1, class: RecordClass::Machine, severity: Severity::Error, reserved: false, description: "The request deadline expired." }),
    (26, CodeRow { name: "MACHINE_OVERFLOW", revision: 1, class: RecordClass::Machine, severity: Severity::Error, reserved: false, description: "Checked non-resource arithmetic overflowed." }),
    (27, CodeRow { name: "MACHINE_ALLOCATION", revision: 1, class: RecordClass::Machine, severity: Severity::Error, reserved: false, description: "Allocation outside a foundation tracked owner failed." }),
    (29, CodeRow { name: "MACHINE_INTERNAL_CONTRACT", revision: 1, class: RecordClass::Machine, severity: Severity::Error, reserved: false, description: "An internal codec or engine contract was violated." }),
    (30, CodeRow { name: "MACHINE_SINK", revision: 1, class: RecordClass::Machine, severity: Severity::Error, reserved: false, description: "The host output sink failed." }),
    (31, CodeRow { name: "MACHINE_SETUP", revision: 1, class: RecordClass::Machine, severity: Severity::Error, reserved: false, description: "The run could not start: an invalid program, codec, format, dialect, or requirement, before any input was read." }),
    (32, CodeRow { name: "MACHINE_RAW_NUL", revision: 1, class: RecordClass::Machine, severity: Severity::Error, reserved: false, description: "A root string dumped raw contains a literal NUL byte, which this process's raw NUL-terminator framing (--raw-output0) cannot represent." }),
    (37, CodeRow { name: "MACHINE_CREDITS", revision: 1, class: RecordClass::Machine, severity: Severity::Error, reserved: false, description: "The cooperative work quantum could not be created: an invalid --cooperative-credits value (a setup failure, pre-input)." }),
    (36, CodeRow { name: "MACHINE_MEMORY", revision: 1, class: RecordClass::Machine, severity: Severity::Error, reserved: false, description: "The allocator-level physical memory ceiling was exceeded (the RSS governor). Distinct from `MACHINE_RESOURCE`: the accounted rejection is the request ledger's own ceiling, this one is the process's real resident set." }),
    (33, CodeRow { name: "PROJECTION_TEMPORAL", revision: 1, class: RecordClass::Informational, severity: Severity::Warning, reserved: false, description: "A date, time, or date-time was rendered as canonical RFC 3339 text because the target has no native temporal spelling." }),
    (34, CodeRow { name: "PROJECTION_TAG", revision: 1, class: RecordClass::Informational, severity: Severity::Warning, reserved: false, description: "A tagged value was published as its bare payload because the target has no native tag spelling." }),
    (35, CodeRow { name: "PROJECTION_BYTES", revision: 1, class: RecordClass::Informational, severity: Severity::Warning, reserved: false, description: "A byte string was rendered as base64url text (RFC 8949 section 6.5) because the target has no native byte-string spelling." }),
    (38, CodeRow { name: "MISMATCH_WARN", revision: 1, class: RecordClass::Informational, severity: Severity::Warning, reserved: false, description: "The mismatch dial's capped, aggregated warn report: one record per run, named after the run, carrying the per-cell counts." }),
    (39, CodeRow { name: "MISMATCH_STRICT", revision: 1, class: RecordClass::Semantic, severity: Severity::Error, reserved: false, description: "A mismatch cell raised under the strict dial; the payload names the cell." }),
    (40, CodeRow { name: "RAISE_ENGINE_CARDINALITY", revision: 1, class: RecordClass::Semantic, severity: Severity::Error, reserved: false, description: "A ~generator init/update/extract emitted two or more values on one pull: one state, one emission, per pull." }),
    (100, CodeRow { name: "FRONTIER_VALIDATION", revision: 1, class: RecordClass::Informational, severity: Severity::Info, reserved: true, description: "Reserved: a projected route validated a corrupt byte the program never read." }),
];

/// Looks one code up by id (the public read path `--explain-code` uses).
#[must_use]
pub fn describe(code: u16) -> Option<&'static CodeRow> {
    CODES.iter().find(|(id, _)| *id == code).map(|(_, row)| row)
}
